version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: onyxchat-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: onyxchat
      POSTGRES_PASSWORD: onyxchat
      POSTGRES_DB: onyxchat
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: 