version: '3.8'
name: onyxchat-dev

services:
  postgres:
    image: postgres:14
    container_name: onyxchat-dev-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: onyxchat
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    restart: unless-stopped
    networks:
      - onyxchat-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  server:
    build:
      context: ./nodejs-server
      dockerfile: Dockerfile
    container_name: onyxchat-dev-server
    ports:
      - "8082:8081"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=onyxchat
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - PORT=8081
      - JWT_SECRET=your_jwt_secret_replace_in_production
      - JWT_REFRESH_SECRET=your_refresh_secret_replace_in_production
      - JWT_EXPIRES_IN=1h
      - JWT_REFRESH_EXPIRES_IN=7d
      - ENCRYPTION_KEY=your_encryption_key_here
    restart: unless-stopped
    networks:
      - onyxchat-network

networks:
  onyxchat-network:
    driver: bridge

volumes:
  postgres_data_dev: 