version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: onyxchat-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: onyxchat
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - onyxchat-network

  server:
    build:
      context: ./nodejs-server
      dockerfile: Dockerfile
    container_name: onyxchat-server
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=onyxchat
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - PORT=8081
      - JWT_SECRET=your_jwt_secret_replace_in_production
      - JWT_REFRESH_SECRET=your_refresh_secret_replace_in_production
      - JWT_EXPIRES_IN=1h
      - JWT_REFRESH_EXPIRES_IN=7d
      - ENCRYPTION_KEY=your_encryption_key_here
    restart: unless-stopped
    networks:
      - onyxchat-network

networks:
  onyxchat-network:
    driver: bridge

volumes:
  postgres_data: 