[package]
name = "onyxchat-server"
version = "0.1.0"
edition = "2021"
authors = ["OnyxChat Team"]
description = "Secure messaging server with end-to-end encryption"

[dependencies]
# Web framework
axum = "0.6.20"
tower-http = { version = "0.4.0", features = ["cors"] }
tokio = { version = "1.33.0", features = ["full"] }

# Logging
tracing = "0.1.40"
tracing-subscriber = "0.3.17"
